name: Restrict to Allowed Paths

on:
  pull_request:

jobs:
  block-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        shell: bash
        run: |
          if [[ "${{ github.head_ref }}" != "base" ]]; then
            echo "Not a PR from 'base' branch, checking which files are modified"
          else
            echo "'base' branch is allowed to modify anything in the codebase"
            exit 0  # 👈 Exit the whole job successfully
          fi

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        shell: bash
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | paste -sd "," -)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Check for restricted path changes
        run: |
          IFS=',' read -ra ITEMS <<< "$CHANGED_FILES"
          for item in "${ITEMS[@]}"; do
            echo $item
          done
          echo "✅ No restricted changes."
