name: Restrict to Allowed Paths

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - reopened

jobs:
  block-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        shell: bash
        id: check
        run: |
          PR_LABELS=$(jq -r '.pull_request.labels | map(.name) | join(",")' "$GITHUB_EVENT_PATH")
          echo "Labels: $PR_LABELS"

          if echo "$PR_LABELS" | grep -q "bypass block-paths"; then
            echo "✅ Label found to not care where changes are for this PR"
            echo "should_continue=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # technically zenith _is_ a fork of LSB, so we have to detect based on repo
          HEAD_REPO="${{ github.event.pull_request.head.repo.full_name }}"
          BASE_REPO="${{ github.repository }}"
          FORK=true
          BRANCH=""

          if [ "$HEAD_REPO" = "$BASE_REPO" ]; then
            FORK=false
          fi

          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            BRANCH="$GITHUB_REF_NAME"
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          fi

          echo "Fork: $FORK"
          echo "Branch: $BRANCH"

          if [ "$FORK" = "false" ] && [ "$BRANCH" = "base" ]; then
            echo "✅ 'base' branch is allowed to modify anything in the codebase"
            echo "should_continue=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$FORK" = "false" ]; then
            echo "All PRs should come from forks."
            echo "Please fork this repository and inform someone about deleting this branch."
            exit 1
          fi

          echo "should_continue=true" >> $GITHUB_OUTPUT

      - name: Check out the code
        if: steps.check.outputs.should_continue == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32

      - name: Check restricted path changes
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          # convert space-delimited list to newline separated
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done | grep -qvE '^modules/zenith-public/' && {
            echo "🚫 Changes to restricted paths detected! Only files inside modules/zenith-public/ are allowed."
            exit 1
          }

          echo "✅ No restricted changes."
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
